spring.application.name=ToDoListWebApplication

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/codekitchen
spring.datasource.username=admin
spring.datasource.password=admin

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=8

# Time Life Session (default 30m)
server.servlet.session.timeout=5m